baseURL = "https://blog.leskor.com"
languageCode = "en-us"
title = "Ruslan's Tech Talk"
description = "Blog by Ruslan Lesko"
theme = "PaperMod"
copyright = "2020 - 2024 Ruslan Lesko"

enableRobotsTXT = true

[params]
keywords = ["Blog", "Ruslan's Tech Talk", "Ruslan Lesko"]
env = "production"
defaultTheme = "auto"
description = "Technology blog by Ruslan Lesko"
comments = false

[params.homeInfoParams]
Title = "Ruslan's Tech Talk"
Content = "Welcome to **Ruslan's Tech Talk**! This is a techonology blog by me, [Ruslan Lesko](https://leskor.com). Please note that here I post personal thoughts, and they may be opinionated. I usually post about programming in Java, technology in general, and lifestyle."

[[params.socialIcons]]
name = "github"
url = "https://github.com/ruslanlesko/fresh"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/LeskoRuslan"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 1

[[menu.main]]
url = "/posts"
name = "Archive"
weight = 2
